### ISSUE TITLE
ModuleNotFoundError: No module named 'skbuild'

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/apriltags#13]
```
Collecting git+https://github.com/pupil-labs/apriltags
  Cloning https://github.com/pupil-labs/apriltags to /tmp/pip-rw9h_3fg-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-rw9h_3fg-build/setup.py", line 11, in <module>
        from skbuild import setup
    ModuleNotFoundError: No module named 'skbuild'
```

Installation via pip fails for older versions pip that do not parse the build dependencies correctly.
We should check the pip version in setup.py and throw an error with a message on how to update pip for older versions of pip!

**Comment by pfaion** [comment]
Note: I had pip version 9.0.1 on Ubuntu 18.04 (system python 3.6.8) when experiencing this issue.

**Comment by pfaion** [comment]
See e.g. this PR to Pupil: https://github.com/pupil-labs/pupil/pull/1775
where a user apparently ran into this problem when installing the dependencies for Pupil.

A good solution could be to just add pip > X as install_requires. Would that work? Need to find the minimal pip version that supports PEP517 and PEP518,

**Comment by pfaion** [comment]
Adding pip to install_requires won't work, as setup.py will be parsed (and skbuild tried to import) before the requirements will be installed.

A quick google did not result in any genius way of how to foolproof a pure PEP517/518 package to be installed from old pip versions. I guess we can only add this to the README here.
