### ISSUE TITLE
Getting requirements to build wheel ... error

### ISSUE THREAD

**Issue by Utsav13** [pupil-labs/apriltags#15]
How to solve this issue ??

```
Getting requirements to build wheel ... error
 ERROR: Command errored out with exit status 1:
   command: /home/robot2/.virtualenvs/cv/bin/python3 /home/robot2/.virtualenvs/cv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp1a45ur0g
       cwd: /home/robot2/apriltags
  Complete output (17 lines):
  Traceback (most recent call last):
    File "/home/robot2/.virtualenvs/cv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/robot2/.virtualenvs/cv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/robot2/.virtualenvs/cv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-p8zgca3k/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-p8zgca3k/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-p8zgca3k/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 18
      cmake_args.append(f"-DPTHREADS_WIN_INCLUDE_DIR='{ptw.include_path}'")
                                                                         ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/robot2/.virtualenvs/cv/bin/python3 /home/robot2/.virtualenvs/cv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp1a45ur0g Check the logs for full command output.
```

**Comment by pfaion** [comment]
Hi @Utsav13,
you seem to be using Python 3.5, but the minimal requirement for pupil-apriltags is Python 3.6.
The error comes from some feature that we are using that are not supported in Python 3.5.
Please upgrade your Python version to 3.6, this should fix the problem!
