### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by mark-belbin** [pupil-labs/apriltags#34]
I receive a segmentation fault when using this library on a Raspberry Pi 4 and python 3.7. When the entire script exits a seg fault pops up. I've attached the following gdb excerpt:

```
[Thread 0x9e2fc460 (LWP 4283) exited]
[Thread 0x9f2fd460 (LWP 4282) exited]
[Thread 0xa02fe460 (LWP 4281) exited]
[Thread 0xa12ff460 (LWP 4280) exited]
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0xaaa33ae8 in quick_decode_uninit ()
   from /home/pi/.local/lib/python3.7/site-packages/pupil_apriltags/lib/libapriltag.so.3
(gdb) backtrace
#0  0xaaa33ae8 in quick_decode_uninit ()
    at /home/pi/.local/lib/python3.7/site-packages/pupil_apriltags/lib/libapriltag.so.3
#1  0xaaa34010 in apriltag_detector_clear_families ()
    at /home/pi/.local/lib/python3.7/site-packages/pupil_apriltags/lib/libapriltag.so.3
(gdb) 
```

The library works fine on windows with the same code, any ideas what would be causing this on a Pi 4?

**Comment by AbdelNabut** [comment]
I'm on a Raspberry Pi 4 and my solution to fixing this was to optimizing my code so as to not run anything unnecessarily in a while loop. For me this was setting at_detector once at the start. I also ran the optimizations mentioned above, but they didn't help me as much as refactoring my code.

**Comment by AnabolicRoo** [comment]
> Receiving same issue. Has there been a resolution?
> 
> Pi4 Python 3.7.3
> 
> Segfault appearing in this portion of code: at_detector = Detector(families='tag36h11', nthreads=2, quad_decimate=1.0, quad_sigma=0.0, refine_edges=1, decode_sharpening=0.25, debug=0)
> 
> Appears to be slightly more stable when nthreads=2 (skips my image if all tags are detected) and crashes if nthreads=1.
> 
> Thanks, Aaron

I encountered the same error with the tag36h11 family. Changing the nthreads value to 2 solved the problem for me.
Here are the detector options I used:
```python
detector_options = {
    "families": 'tag36h11', "quad_decimate": 1.0, "quad_sigma": 0.0,
    "refine_edges": True, "decode_sharpening": 0.25, "nthreads": 2
}
```

**Comment by hjkornn-phys** [comment]
* Solution that works on my machine (on __del__ of detector)

with help of GPT-5, I implemented `safe_close_detector` and it helped mem-safe destruction
```
def safe_close_detector(det):
    # Best-effort, idempotent cleanup
    try:
        libc = det.libc
    except AttributeError:
        return
    try:
        # Ensure correct signatures once
        if hasattr(libc, "apriltag_detector_destroy"):
            libc.apriltag_detector_destroy.restype = None
        for fname in (
            "tag16h5_destroy","tag25h9_destroy","tag36h11_destroy",
            "tagCircle21h7_destroy","tagCircle49h12_destroy",
            "tagCustom48h12_destroy","tagStandard41h12_destroy","tagStandard52h13_destroy",
        ):
            f = getattr(libc, fname, None)
            if f is not None:
                f.restype = None

        # Destroy detector first
        td = getattr(det, "tag_detector_ptr", None)
        if td:
            try:
                libc.apriltag_detector_destroy(td)
            except Exception:
                pass
            det.tag_detector_ptr = None

        # Then destroy families you created
        fams = dict(getattr(det, "tag_families", {}) or {})
        for name, tf in fams.items():
            destroy = getattr(libc, f"{name}_destroy", None)
            if destroy is None:
                # map known aliases
                alias = {
                    "tag16h5":"tag16h5_destroy","tag25h9":"tag25h9_destroy","tag36h11":"tag36h11_destroy",
                    "tagCircle21h7":"tagCircle21h7_destroy","tagCircle49h12":"tagCircle49h12_destroy",
                    "tagCustom48h12":"tagCustom48h12_destroy","tagStandard41h12":"tagStandard41h12_destroy",
                    "tagStandard52h13":"tagStandard52h13_destroy",
                }.get(name)
                destroy = getattr(libc, alias, None) if alias else None
            try:
                if destroy:
                    destroy(tf)
            except Exception:
                pass
        # Scrub to make __del__ a no-op
        try:
            det.tag_families.clear()
        except Exception:
            det.tag_families = {}
    except Exception:
        pass
```
