### ISSUE TITLE
FileNotFoundError: [WinError 206] The filename or extension is too long in pupil_apriltags

### ISSUE THREAD

**Issue by sina-razaghi** [pupil-labs/apriltags#55]
A program has been written to check a series of tags during an approximately 2-3 minute video and we check these tags using the pupil_apritag library. A detailed and quick check is done, but the problem is in doing it in the long term. I didn't use the library to save, I just save a bunch of numbers, but this library gives an error like this:

--------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "g:\Code_HIT_A_V3.py", line 66, in <module>
    sign = function_V3.detect_sign_apriltag(image[100:400, 280:512])
  File "g:\function_V3.py", line 109, in detect_sign_apriltag
    detector = Detector(
  File "C:\Users\Sina\AppData\Local\Programs\Python\Python310\lib\site-packages\pupil_apriltags\bindings.py", line 336, in __init__
    dll_dir = os.add_dll_directory(dll_path)
  File "C:\Users\Sina\AppData\Local\Programs\Python\Python310\lib\os.py", line 1117, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 206] The filename or extension is too long: 'C:\\Users\\Sina\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\pupil_apriltags\\lib'
--------------------------------------------------------------------------------------------

The program runs for about 1 minute and 30 seconds and suddenly crashes. I will also give you a part of the code on the library side that gets an error:

--------------------------------------------------------------------------------------------
def add_dll_directory(path):
    """Add a path to the DLL search path.

    This search path is used when resolving dependencies for imported
    extension modules (the module itself is resolved through sys.path),
    and also by ctypes.

    Remove the directory by calling close() on the returned object or
    using it in a with statement.
    """
    import nt
    cookie = nt._add_dll_directory(path)
    return _AddedDllDirectory(
        path,
        cookie,
        nt._remove_dll_directory
    )
--------------------------------------------------------------------------------------------

I use python 3.10.7 and last version of pip
I found almost no explanation or guidance on the internet about this.

**Comment by MadSuleiman** [comment]
Seconding this. I'm experiencing the same issue as I'm running aprildetect on a flask webserver. It stops functioning after about a minute as well. My code is almost identical to the above.

**Comment by FarV-Ma** [comment]
This is because the pupil version of binding is based on an out-of-date version of apriltag library. If you don't want to compile the dlls lib from newer source code from [[AprilRobotics/apriltag](https://github.com/AprilRobotics/apriltag)] by yourself, just change to [pyapriltags](https://github.com/WillB97/pyapriltags) binding with `pip install pyapriltags`.

**Comment by QueeneTam** [comment]
> This is because the pupil version of binding is based on an out-of-date version of apriltag library. If you don't want to compile the dlls lib from newer source code from [[AprilRobotics/apriltag](https://github.com/AprilRobotics/apriltag)] by yourself, just change to [pyapriltags](https://github.com/WillB97/pyapriltags) binding with `pip install pyapriltags`.

Hi, I use the recommendation that install puapriltags, but the error still exists.
The puapriltags version I installed is pyapriltags-3.4.3.1.
Do you have any other idea on how to solve the filename or extension too long problem?
