### ISSUE TITLE
windows env error, self.tag_detector_ptr = self.libc.apriltag_detector_create()

### ISSUE THREAD

**Issue by TangLeeee** [pupil-labs/apriltags#58]
python version: 3.9.16
widows11

I've view all the others' issue, none fix my problem.

firstly, as common 
`import pupil_apriltags as apriltag
detector = apriltag.Detector()
`
then get error
FileNotFoundError: Could not find module 'C:\Users\yuanpei.lin\AppData\Roaming\Python\Python39\site-packages\pupil_apriltags\lib\apriltag.dll' (or one of its dependencies). Try using the full path with constructor syntax.

after searching a long time, I change line:337 in bindings.py
`self.libc = ctypes.CDLL(str(hit), winmode=1)`
(winmode=0 doesn't work for me, nothing changes, and I found a similar problem menthioned in stackoverflow so I change to winmode=1)

but still get error like this:
  File "C:\Users\***\AppData\Roaming\Python\Python39\site-packages\pupil_apriltags\bindings.py", line 351, in __init__
    self.tag_detector_ptr = self.libc.apriltag_detector_create()
OSError: exception: access violation writing 0x00000000006338BE

BTW: I've tried python3.7, it seems work for most others but not me, i got the error msg in python3.7 like:
OSError: [WinError 193] %1 is not valid Win32 application.
Exception ignored in: <function Detector.__del__ at 0x000001A604BDF048>
Traceback (most recent call last):
  File "D:\apps\miniconda3\envs\python37\lib\site-packages\pupil_apriltags\bindings.py", line 420, in __del__
    if self.tag_detector_ptr is not None:
AttributeError: 'Detector' object has no attribute 'tag_detector_ptr'

I'm really confused!
So anyone can help?

**Comment by djascorp** [comment]
Same Error.
