### ISSUE TITLE
Could not find module

### ISSUE THREAD

**Issue by PetSven** [pupil-labs/apriltags#64]
I am using Windows 11, Python 3.12.5 and library version 1.0.4.post10. I get the following error message when I try to run the example code. I see other people had this issue in the past, but it was fixed. Maybe this fix no longer works?

> C:\Users\[user]\AppData\Local\Programs\Python\Python312\Lib\site-packages\pupil_apriltags\lib
Traceback (most recent call last):
  File "C:\Users\[user]\OneDrive\[folder]\[folder]\MyAprilTag.py", line 19, in <module>
    at_detector = Detector(
                  ^^^^^^^^^
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python312\Lib\site-packages\pupil_apriltags\bindings.py", line 340, in __init__
    self.libc = ctypes.CDLL(str(hit))
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\[user]\AppData\Local\Programs\Python\Python312\Lib\site-packages\pupil_apriltags\lib\apriltag.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by ThePyProgrammer** [comment]
I face this same issue with Python 3.9.16 🤔 does anyone know what the issue could be?
